### ISSUE TITLE
프로젝트를 위해 이 모듈을쓰려고합니다.

### ISSUE THREAD

**Issue by qqqqpppp** [jiru/kakaodecrypt#1]
아직도 복호화가 되는건가요? 돌려보면 
C:\pentest\virus>python decryt.py -p KakaoTalk.db
1|1504226982476158976|1|169654773776406|240440409|pBO6rG5DQmOOfRwyoV6nqw==|None|1500255029|0|743764879|1504219690368274433|{"origin":"MCHATLOGS","defaultEmoticonsCount":0,"isMine":false,"notDecoded":false,"c":"07-17 10:41:58","isSingleDefaultEmoticon":false,"enc":22}
2|1504229712213088256|1|169654773776406|240440409|Ah06VZFMkDYZTdUrbrBb77fLJjvbAuv1xjrAkaLOdkQ=|{}|1500255355|0|1311838799|1504226982476158976|{"origin":"MCHATLOGS","defaultEmoticonsCount":0,"isMine":false,"notDecoded":false,"c":"07-17 10:41:58","isSingleDefaultEmoticon":false,"enc":22}
3|1504231764695846913|1|173183388153071|3741085|6U/FA+Cva5b84+EsB/MOXQ==|None|1500255599|0|745694590|1504218710151079936|{"origin":"MCHATLOGS","defaultEmoticonsCount":0,"isMine":false,"notDecoded":false,"c":"07-17 10:41:58","isSingleDefaultEmoticon":false,"enc":22}
이러한 애러가 뜹니다

**Comment by jiru** [comment]
Thank you! Try with the latest HEAD, this should be fixed now.
