### ISSUE TITLE
Unsupported encoding type 28

### ISSUE THREAD

**Issue by Blackiris-no1** [jiru/kakaodecrypt#10]
Traceback (most recent call last):
  File "kakaodecrypt.py", line 19, in genSalt
    salt = prefixes[encType] + str(user_id)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kakaodecrypt.py", line 207, in <module>
    KakaoDbDecrypt.run(db_file, enc_table, dec_table, enc_fields, do_print)
  File "kakaodecrypt.py", line 167, in run
    contents = KakaoDecrypt.decrypt(user_id, enc_type, contents)
  File "kakaodecrypt.py", line 91, in decrypt
    salt = KakaoDecrypt.genSalt(user_id, encType)
  File "kakaodecrypt.py", line 22, in genSalt
    raise ValueError('Unsupported encoding type %i' % encType)
ValueError: Unsupported encoding type 28

**Comment by jiru** [comment]
The file you are trying to decode is too recent. Kakaodecrypt needs to be updated to support it.

**Comment by Blackiris-no1** [comment]
> The file you are trying to decode is too recent. Kakaodecrypt needs to be updated to support it.

 Can you update kakaodecrypt?
Or can you please let me know if there is a way to refer to the update?

**Comment by Blackiris-no1** [comment]
> The file you are trying to decode is too recent. Kakaodecrypt needs to be updated to support it.

If you need a db file
You can send it by email.

**Comment by jiru** [comment]
I meant somebody needs to add support. I can take care it. Thanks for offering your help. You can send me the database by email at kakao28.gillux@spamgourmet.com.

**Comment by Blackiris-no1** [comment]
> The file you are trying to decode is too recent. Kakaodecrypt needs to be updated to support it.

Please check the email :)

**Comment by jiru** [comment]
I added support for encoding 28 and 29.
