### ISSUE TITLE
not table exist

### ISSUE THREAD

**Issue by adgjmptw2** [jiru/kakaodecrypt#12]
C:\Users\123\Desktop\kakaodecrypt-master>python kakaodecrypt.py -p KakaoTalk.db

C:\Users\123\Desktop\kakaodecrypt-master>

and open kakaotalk.db ->
table (0)
index (0)
view (0)
trigger (0)
DB browser for sqlite

**Comment by jiru** [comment]
Are you sure the file KakaoTalk.db contains anything in the first place?
By the way, option `-p` is for printing out. Omit it to make it create tables with decrypted contents.

**Comment by adgjmptw2** [comment]
![image](https://user-images.githubusercontent.com/41006577/105535102-c2ec9f80-5d31-11eb-9706-e5ff79bf98ee.png)
and
![image](https://user-images.githubusercontent.com/41006577/105535126-caac4400-5d31-11eb-92bd-c48c19e89b9d.png)
no decrypt
![image](https://user-images.githubusercontent.com/41006577/105535170-e0216e00-5d31-11eb-8785-087680e3e565.png)
decrypt like first pic that mean cant find table
can u help me ?? sry if u can discord dm my discord is MINE#0001 thank you..

**Comment by adgjmptw2** [comment]
![image](https://user-images.githubusercontent.com/41006577/105536760-32638e80-5d34-11eb-9392-e3c7a01852da.png)
![image](https://user-images.githubusercontent.com/41006577/105536779-3a233300-5d34-11eb-907e-98577d623374.png)
hmm how to fix it?

**Comment by jiru** [comment]
I don't see any problem. Your first screenshot shows the chat logs have been decrypted into the table `chat_logs_dec` (and also printed out when you used `-p`). Try opening that table.

About your second screenshot, it shows the original table `chat_rooms`. It's normal that this table is encrypted. To decrypt it as well, you need to specify the user id of the account with option `-u`. Try running `python guess_user_id.py KakaoTalk.db` to get the user id.

**Comment by adgjmptw2** [comment]
![image](https://user-images.githubusercontent.com/41006577/105718814-fd8a4e00-5f64-11eb-8603-420aa565f5c4.png)
![image](https://user-images.githubusercontent.com/41006577/105719255-6bcf1080-5f65-11eb-8d5d-26865b84f888.png)
sry  im noob

**Comment by jiru** [comment]
In the second screenshot you posted, it looks like you are able to decrypt the table `chat_logs` but kakaodecrypt fails to decrypt the table `chat_rooms`. Do you mind sending me your `KakaoTalk.db` file so I can investigate the problem? You can upload it to https://lufi.stemy.me/ and post the download link here. Then I will quickly remove your comment.

**Comment by adgjmptw2** [comment]
https://lufi.stemy.me/r/YaCBSKxZwD#1XFQI3snTe1kgFHVgnAWuOakjno/Hd6RfYPKG30vnU0=

**Comment by jiru** [comment]
Thanks, I fixed the problem. It’s likely that your file contains an invalid row in the `chat_rooms` table. I assume it happened because of a bug in KakaoTalk or something.
