### ISSUE TITLE
KeyError:'enc'

### ISSUE THREAD

**Issue by Blackiris-no1** [jiru/kakaodecrypt#13]
Traceback (most recent call last):
  File "kakaodecrypt.py", line 181, in run
    enc_type = row[ col_defs['enc'] ]
KeyError: 'enc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kakaodecrypt.py", line 239, in <module>
    KakaoDbDecrypt.run(args.db_file, enc_table, dec_table, enc_fields, args.p, args.u)
  File "kakaodecrypt.py", line 189, in run
    enc_type = v_data['enc']
KeyError: 'enc'

**Comment by jiru** [comment]
May I see the file you are trying to decrypt?

**Comment by Blackiris-no1** [comment]
> May I see the file you are trying to decrypt?

of course.
Please provide an email address to receive the file.

General decryption is possible.
The problem area is
In case of using -u option

**Comment by jiru** [comment]
You can send it to 13.kkd@xoxy.net.

**Comment by jiru** [comment]
May I see the complete command line that gives this error?

**Comment by Blackiris-no1** [comment]
> May I see the complete command line that gives this error?

okay.

<img width="1168" alt="스크린샷 2021-03-13 오후 6 15 39" src="https://user-images.githubusercontent.com/63716607/111025564-48cec200-8428-11eb-9753-198a0043029b.png">

**Comment by Blackiris-no1** [comment]
> May I see the complete command line that gives this error?

I sent the KakaoTalk db file by e-mail.

The overall command line command is replaced with the picture above.

**Comment by jiru** [comment]
It looks like couldn’t get your email because the attachment was too big. Could you try again compressing the file into a ZIP or uploading it to a temporary place?

**Comment by jiru** [comment]
Note that from the above screenshot, we can tell that the chat logs were decrypted successfully into the new table `chat_logs_dec`. The error comes from one of the other tables Kakaodecrypt is trying to read.

**Comment by jiru** [comment]
Closing as I did not get reply from Blackiris-no1.
