### ISSUE TITLE
Echo ERROR "list index out of range" when encType = 31

### ISSUE THREAD

**Issue by linliyuan** [jiru/kakaodecrypt#14]
Be use like 
contents = KakaoDecrypt.decrypt(387216304, 31, "RcrN4TWyfEL0p6O+yWtOpw==")

![image](https://github.com/jiru/kakaodecrypt/assets/37769385/f967b3b9-9f65-43bf-a31c-50a148f67568)

**Comment by linliyuan** [comment]
add 31 key is  'veil'

**Comment by ghost** [comment]
Thank you!
How can I get key when the encType is changed?

**Comment by jiru** [comment]
Thank you for reporting, I added support for encoding type 31.
