### ISSUE TITLE
 KeyError 'enc' (similar to issue #13)

### ISSUE THREAD

**Issue by SoulMorong** [jiru/kakaodecrypt#15]
First, sorry for my bad English :(

I have KeyError 'enc' similar to issue #13 
chat_logs are successfully decoded and make chat_logs_dec table, but i think there is an issue decoding chat_rooms.

Here is  my error log:

```
PS kakaodecrypt-master> python .\kakaodecrypt.py -u 54976745 apps\com.kakao.talk\db\KakaoTalk.db
Created table 'chat_logs_dec'.
Traceback (most recent call last):
  File "\kakaodecrypt.py", line 197, in run
    enc_type = row[ col_defs['enc'] ]
KeyError: 'enc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kakaodecrypt.py", line 255, in <module>
    KakaoDbDecrypt.run(args.db_file, enc_table, dec_table, enc_fields, args.p, args.u)
  File "kakaodecrypt.py", line 205, in run
    enc_type = v_data['enc']
KeyError: 'enc'
```
and codes where error appeared:
![image](https://github.com/jiru/kakaodecrypt/assets/122333350/49873c86-eaf1-49ca-b961-43c6510df28b)

using env : windows 10 pro version 22H2 (os build 19045.3803)
python 3.9.13 64-bit
pycrypthodome, pycryptodome == 3.19.0

I uploaded my kakaotalk.db file at google drive.
If u need db file, let me know how to share file link (like e-mail address or something else).
Thank you.

**Comment by jiru** [comment]
You can send the database file to [13.kkd@xoxy.net](mailto:13.kkd@xoxy.net). Please compress the file into a ZIP or similar.

**Comment by jiru** [comment]
Thank you for your help, the problem should be solved now.
