### ISSUE TITLE
Error from Crypto.Cipher import AES

### ISSUE THREAD

**Issue by onurasln55** [jiru/kakaodecrypt#4]
Traceback (most recent call last):
  File "C:/Users/..../PycharmProjects/kakaode/talk.py", line 3, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by jiru** [comment]
You need to have Pycryptodome installed.

https://github.com/Legrandin/pycryptodome/issues/174
https://stackoverflow.com/questions/31485110/no-module-named-crypto-cipher/31485157
https://www.pycryptodome.org/en/latest/src/installation.html
